### PR TITLE
Add test packages and clickOutside tests

### PR DESCRIPTION
**Pull request by geoffrich**
This PR adds initial test setup and clickOutside tests (#5).

I picked mocha/jsdom/sucrase since that's what the main svelte repo uses. This should make it easy to port over the tests if these actions become official. sinon isn't used in the main svelte repo but it makes callback verification easy.

This PR also refactors lazyload to only init IntersectionObserver when the action is used (though still using a shared IntersectionObserver). Without this change, tests were failing with an "IntersectionObserver is not defined" ReferenceError. This kicks that can down the road until we go to write lazyload tests.

I wanted to get feedback on test structure and setup before writing tests for the other actions.

### CODE REVIEW

**Comment by sw-yx** [comment]
that's awesome!

**Comment by sw-yx** [comment]
that's awesome @geoffrich! thanks so much for getting the ball rolling on this, it is sorely needed :)

i was thinking that this would happen someday and its probably time - what do you think about colocating the test to the action?

image

this would make it easy to find/modify/delete, and then we would manually manage `index.ts` and `test.ts` to require and export them.

i dont feel SUPER strongly about this, just proposing it as a straw man. honestly i dont intend this project to be that big that folder structure would ever really be a problem

**Comment by geoffrich** [comment]
@sw-yx that makes sense to me! I moved each action into its own file and moved the tests into the `src` folder as described. The `Action` type is in its own file now too so the individual actions can import it. Let me know what you think.

**Comment by sw-yx** [comment]
i like it :)

**Pull request merged**
